- name: Update All Servers
  hosts: all
  become: yes
  tasks:
    - name: Update Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update RHEL/CentOS/Oracle systems
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
